### ISSUE TITLE
allPerms() returns fewer permutations than expected

### ISSUE THREAD

**Issue by andersgs** [gavinsimpson/permute#20]
I want all permutations of 5 elements. My own calculations set that at 120 possible permutations. A number that `permute::numPerms(5)` agrees with, yet when running  `permute::allPerms(5)` I only get 119 rows. One is missing!

Have I done something wrong?

Running version `0.9-4`.

Thank you. 

Anders.

**Comment by jarioksa** [comment]
You did not read the help file?

> ‘allPerms’ returns a matrix
     containing all possible permutations, possibly containing the
     observed ordering (if argument ‘observed’ is ‘TRUE’).

The function leaves out the observed order `1:5` unless you ask it returned. Doing this can be a bit tricky, though: you must define `observed` using `how()`:
```R
allPerms(5, control = how(observed = TRUE))
```

**Comment by andersgs** [comment]
Argh. Thank you. I did look at the help file, but missed that crucial line. Seems counter-intuitive, though. The function is `allPerms`, not `missingPerms`.

**Comment by jarioksa** [comment]
The crux is how we use permutations: the standard way is to put the observed statistic among permutation statistics, and if we have the original order already in permutations, we got it twice. So we ask for all - 1 permutations (119 in this case), and when we compare the observed statistic (1) against permutations, we add back the observed one and got them all (120). Using `allPerms` is a margin case: usually we just generate permutations from such a high number of possible permutations that we do no need to care about the very low probability of duplicating the observation (or duplicating any other in the set). We switch to `allPerms` when the duplication risk is high.

**Comment by jarioksa** [comment]
@andersgs , you may have a look at issue #10 where we discuss the use of `allPerms`.

**Comment by gavinsimpson** [comment]
@andersgs `missingPerms` would be a misnomer too... As @jarioksa mentioned, the motivation for the code in **permute** is for permutation tests and in such instances one already has the observed permutation so why bother returning it? **permute** was never intended as a general purpose package for combinatorics; there are other R packages for that.
