### ISSUE TITLE
Documentation for how() doesn't describe the options for Type=

### ISSUE THREAD

**Issue by glaroc** [gavinsimpson/permute#22]
The description for type says "character; the type of permutations required. One of "free", "series", "grid" or "none". See Details.". But there is no mention of that in the Details.

**Comment by jarioksa** [comment]
This is the canonical way of documentation in R, isn't it? Details do not repeat description, but they can *add* detail when needed. The Details do expand on the usage of `how` in defining permutation, like indicated in Description.

**Comment by glaroc** [comment]
So we have to read the vignette to know what the type= argument means?

**Comment by gavinsimpson** [comment]
But Details should explain briefly what each does, e.g.

> Argument `type` controls how samples are actually permuted; `"free"` indicates randomization, `"series"` indicates permutation via cyclic shifts (suitable for evenly-space line transect or time series data), `"grid"` indicates permutation via toroidal shifts for samples on a regular grid, and `"none"` indicates no permutation of samples. See the package vignette (`browseVignettes("permute")`) for additional detail.

?
