### ISSUE TITLE
check fails to set nperm to number of permutations when complete = TRUE

### ISSUE THREAD

**Issue by gavinsimpson** [gavinsimpson/permute#23]
If a user really wants complete enumeration, `check()` should set `nperm` in the permutation design to the number of permutations generated for the complete set.

With this example data

```r
library(vegan)
data(mite)
mite <- mite[1:9, ]
mite <- mite[, colSums(mite)!=0]
mite <- mite[,1:14]
site <- gl(3,3)
site
```

If we do:

```r
ctrl <- how(complete=TRUE, maxperm=500000)
rda2 <- anova(rda(mite~site), permutations = ctrl)
rda2
attributes(rda2)
```

You'll notice that `anova()` sits for a long time, but then only uses 199 permutations. The long wait is when `check()` generates all 300000+ permutations but these don't get used. `rda2` reports only 199 permutations used.

**Comment by jarioksa** [comment]
What do you mean with **really** wanting: do you assume the user knows what this wanting really means? If does need much to want more permutations than there are atoms in the known universe, and even less to run over `MAXINT`.

**Comment by gavinsimpson** [comment]
@jarioksa I mean they set `complete = TRUE` and increased `maxperm` accordingly. At the moment we detect this in `check()` but don't update `nperm` in the permutation design, and also when we call `check()` in `shuffleSet()` we don't update `nset` with the potentially now modified `nperm` *after* `check() has returned.

I'll add the example I was sent enquiring about this, via email, in the initial Issue comment.

**Comment by jarioksa** [comment]
Yep, this makes sense.
