### ISSUE TITLE
CRAN version failing tests under R-Devel

### ISSUE THREAD

**Issue by gavinsimpson** [gavinsimpson/permute#25]
The CRAN version of *permute* is failing the tests under R-Devel. This is related to a bug in the random number generator for uniform random sampling and which affects `sample()` in particular.

Ideally, *permute* would require R >= 3.6.0 when R-Devel is released as R 3.6.0 as the bias in the random sampling could affect users if they are permuting very large sets of indices. This is probably not a major use-case for the package as it would be painfully slow, but as *permute*'s sole job is to do this kind of randomization, we should be cognisant of it. Bumping the minimum R requirement would have knock on consequences for *vegan*.

For now, the situation can be handled by adding

```r
suppressWarnings(RNGversion("3.5.0"))
```

before calls to `set.seed()` where differences between `RNGversion`s are causing tests, examples, vignettes to fail.

The message from Kurt (on behalf of CRAN) included the following note (hint):

> Note also that the new "Rejection" sampler which R will use from 3.6.0
> onwards by default is definitely preferable over the old one, so that
> the above should really only be used as a temporary measure for
> reproduction of the previous behavior (and the run time tests relying on
> it).

So there is a steer here that we may need to just use the suggested fix temporarily and we should consider the implications for *vegan* as we address the proximal issue of which RNG version to use.

This needs to be fixed (in the temporary fashion via `RNGversion()`) by March 20th, 2019.

@jarioksa do you have any comments/input on this or the broader issue? I propose now just to do the temporary fix but input on how requiring R >= 3.6.0 might affect *vegan* is also welcome.

**Comment by jarioksa** [comment]
A quick look: it seems that actually **permute** fails **testthat** tests. The random number sequences change which would be a warning normally, but elevated to failure by **testthat**. I haven't built **R-devel** since the last **vegan** release, and I haven't noticed this RNG change, and I haven't checked how it influences **vegan** tests. Anyway, if **R** changes, you got to change along – no choice. This is such a common case that there is even a song about it:

> I feel the R move under my feet
I feel the sky tumbling down
I feel my heart start to trembling ...

**Comment by gavinsimpson** [comment]
@jarioksa Right; the proximal failure is the unit tests as the default RNGversion differs between 3.5 and 3.6 (to be). I've fixed this locally now.

The main issue that affects vegan is if I depend on R 3.6 (I don't have to, but the recommendation would be to use the unbiased sampler that is only available from 3.6 onwards) then that sets a practical lower R version of 3.6.0 also for vegan even if it itself only need 3.3.0 onwards.

Perhaps this isn't as big an issue for you now as you are retired. But I did want to check before making such a change.

I think I have fixed all the areas where there are differences/failures now and can reproduce results/output on R-release and R-devel, using the temporary fix. I'll push this to CRAN early next week, and think about what to do re dependency on R 3.6.0 when it is released.

**Comment by jarioksa** [comment]
Gav, the problem is with the tests and changing RNG in **R**. This has happened before in **R**. All you need to do is to change the reference output for tests so that they pass new **R**, and notify **CRAN** that due to change in their RNG, older versions will fail. No need to add dependence just because of the **testthat**ly retention.

**Comment by gavinsimpson** [comment]
@jarioksa I've already fixed all these trivial tests issue and inconsistent output from examples (which are also checked and differ under R-Devel). That was the easy bit.

CRAN won't allow failures against R-devel now; I've had to force the *old* behaviour on all systems. Likewise, they do test against old-release and unless one has a dependence on a later version of R, my understanding is that they won't allow failing packages. If it doesn't work on R 3.5.0 when it becomes old-release I anticipate issues with CRAN not accepting the package if it doesn't declare the appropriate dependency on R 3.6.0.

There's nothing stopping us sticking with the old version for tests, and allowing *permute* use under older R versions with biased RNGs.

The broader issue is whether, in the interests of having *permute* work reliably, I decide to require R >= 3.6.0 for *permute*. I don't have to, but if I didn't have to consider *vegan* I would probably add this dependency to insist on the more reliable RNG when using *permute* as someone might be using it for problems where they encounter the bias in the current RNG. However, if I did do this, *vegan* would then have a *de facto* requirement for R >= 3.6.0 too.

It is this latter issue I was wanting input on; if you'd prefer to keep *vegan* operating on earlier R versions, I won't require 3.6.0. If you don't mind, I'll add the requirement for R >= 3.6.0 when it is released (well, shortly after to give time for early issue and binaries to be built for all OSes).

**Comment by jarioksa** [comment]
Gav, Is it really so that the only thing that changes are random number sequences in **R** RNG? And the only thing that fails are tests that assume a certain sequence? That is, there is no change in **R** code or API in **permute**? It the only things that fails are tests having wrong assumptions, then this very much sounds a self-inflicted damage – not quite like Brexit, but in the same vein.  The tests should not ERROR if you fix the infrastructure (**R** RNG). Neither should you force the old RNG – I would call this anti-social behaviour and put an ASBO on that. When a user upgrades **R** – in particular when she does so to get the improved RNG – she should get upgraded **R**. The tests just **must** pass irrespective of the infrastructure, or they may pass with warning suggesting an **R** upgrade, but there should be no error.

**Comment by gavinsimpson** [comment]
I think we're talking at cross purposes @jarioksa. Ignore the tests; there is a way to ensure common output on R 3.5 and future R versions, the need for which will go away once 3.6 is old-release if we choose to do *nothing* beyond fix the tests. I've already fixed this issue and have submitted the package to CRAN.

What I'm getting at is that the current 3.5 version of the RNG is biased for some (admittedly obscure) use cases. *permute*'s only reason for being is to generate random (restricted) permutations. If the means by which it does that (i.e. `sample()`) is biased, then an argument could be made that in light of the bias in the 3.5 RNG that *permute* **should** insist on the unbiased RNG in 3.6 onwards (once it is released), and thence once 3.6 is released I should require R >= 3.6.0 for *permute* and push a new version of the package to CRAN then.

Put it another way. There are situations where *permute* would not give random permutations under the 3.5 RNG; it gives **incorrect** outputs. To fix that *bug*, an argument can be made that *permute* shouldn't work with the 3.5 RNG but require the 3.6 RNG or later.

This is nothing to do with tests. This is about returning correct permutations.

Now, the situations where *permute* might return incorrect/biased permutations are very small and unlikely to affect many users (but what do I know? *permute* keeps on cropping up in all sorts of places that I have little comprehension of.) 

If all I was concerned with was *permute* I'd add a dependency on R >= 3.6.0 shortly after that version was released because someone *could* be using *permute* with the 3.5 RNG and be getting biased permutations. But I don't only have *permute* to think about. Primarily I concern myself with *vegan*. I know that some university's IT departments are slow to upgrade R, which is why we've been loath to use the latest functions introduced in newer versions of R without good reason, or you've back-ported things to make *vegan* work. That's all I really wanted your input on, not the testing stuff.

Of course, I can't stop someone using *permute* with R 3.5.x, but I can stop anyone from installing *permute* on R < 3.6.0 for new installs of the package.

Another option would be to update *permute* to spit out a message upon loading & attaching the package to warn users about using it on R < 3.6.0.

**Comment by jarioksa** [comment]
I suggest a (loud) warning against old **R**. **permute** provides just an interface to **R**, and if the interface does not change, there is no reason to change **R** dependence.

**Comment by gavinsimpson** [comment]
Ok, I'll go that route once R 3.6.0 is ready for release.

**Comment by gavinsimpson** [comment]
As vegan now depends on R >= 4.1.0 I guess I can likewise depend on >= 3.6.0 so I will do that.
