### ISSUE TITLE
Add a startup message to warn about issues with RNG in R <= 3.5.3

### ISSUE THREAD

**Issue by gavinsimpson** [gavinsimpson/permute#26]
As discussed in #25 add a startup message to warn about using *permute* with versions of R <= 3.5.3. This is to avoid placing a dependency on R >= 3.6.0 (when it is released) which has knock-on effects for packages that depend on *permute*.

**Comment by jarioksa** [comment]
The current **R** release seems to be 3.5-3: so R <= 3.5.3. The latest major change in RNG seemed to happen in R > 1.6 when `"Marsaglia-Multicarry", "Buggy Kinderman-Ramage"` was replaced with `"Mersenne-Twister", "Inversion"`.

**Comment by gavinsimpson** [comment]
Ooops, quite right @jarioksa
