### ISSUE TITLE
shuffleFree uses sample.int incorrectly

### ISSUE THREAD

**Issue by MichaelChirico** [gavinsimpson/permute#29]
```
Sys.setenv("_R_CHECK_LENGTH_1_LOGIC2_"="true")
shuffleFree(1:10, 1)
# Error in !replace && is.null(prob) && size <= n/2 : 
#   'length(x) = 10 > 1' in coercion to 'logical(1)'
```

The problem is the `n` argument to `sample.int()` is supposed to be a scalar

The example is taken from shuffle-utils.Rd, so the following will fail:

```
_R_CHECK_LENGTH_1_LOGIC2_=true R CMD check permute
```

There are a couple of (I assume obvious) fixes but I'm not sure the intent here.

**Comment by gavinsimpson** [comment]
Thanks @MichaelChirico. Brian Ripley reported this on behalf of CRAN a few days back. I have fixed this locally and have prepared to send a fixed version to CRAN but reverse dependency checks too a while to get working and completed. Assuming they are all clear when I check the laptop shortly I'll push the changes to GH and do final checks for releasing to CRAN.

**Comment by MichaelChirico** [comment]
Great! Just noticed the errors on CRAN. Feel free to close this whenever you'd like then

**Comment by gavinsimpson** [comment]
This is now fixed; will release to CRAN shortly.
