### ISSUE TITLE
`how(blocks = NULL)` fails

### ISSUE THREAD

**Issue by jarioksa** [gavinsimpson/permute#8]
I got this query from Pierre Legendre. He has a script where permutation `blocks` are either a factor or `NULL`, but this seems to fail:
```R
> how(blocks=NULL)
Error in how(blocks = NULL) : 
  'names' attribute [2] must be the same length as the vector [1]
```
This is surprising, since `blocks = NULL` is the default of `how()`. 

This seems to happen because `how` processes its `call`:
```R
    ## process the call to make it standalone
    .call <- match.call()
    if (length(.call) > 1L) {
        .ll <- as.list(.call[-1])
        args <- names(.call)[-1]
        ## evaluate arguments other than within and plots
        ## those handled in their respective functions
        for (i in args[!args %in% c("within","plots")]) {
            .ll[[i]] <- eval(.ll[[i]], parent.frame())
        }
    }
```
If we had a call `how(blocks = NULL)`, we have at the outer loop
```R
 str(.ll)
List of 1
 $ blocks: NULL
```
And when evaluate that it will be removed:
```R
 eval(.ll[[1]])
NULL
```
That is, there will an empty list and `blocks` is lost. Then much later we try to set the names of `.ll` to match `.call` and we get the error at the loop where we `## finsh off`

I don't have time to look at this any closer now. Just for the record.

**Comment by gavinsimpson** [comment]
Thanks @jarioksa I'll take a look at this too, but might take me a day or two as I'm away at a conference at the moment.

**Comment by gavinsimpson** [comment]
Hi @jarioksa I just added a check to only evaluate the parts of the call if they are no `NULL`, which seems to be working now.
